/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SensorsAdmin;

import business.Enterprise.Enterprise;
import business.Organisation.Organisation;
import business.Organisation.SensorsOrganisation;
import business.Organisation.TransportationOrganisation;
import business.Sensor.CollisionSensor;
import business.UserAccount.UserAccount;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.CollisionSensorThread;

/**
 *
 * @author aksha
 */
public class CollisionSensorParamJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private CollisionSensor collisionSensor;
    private SensorsOrganisation sensorsOrganisation;

    /**
     * Creates new form CollisionSensorParamJPanel
     */
    public CollisionSensorParamJPanel(JPanel userProcessContainer,UserAccount userAccount,Organisation organisation,Enterprise enterprise,CollisionSensor collisionSensor){
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.sensorsOrganisation = (SensorsOrganisation)organisation;
        this.collisionSensor = collisionSensor;
        CollisionSensorThread cst = new CollisionSensorThread(userAccount, organisation, this,collisionSensor);
        cst.start();
    }
    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel)collisionParamjTable2.getModel();
        
        Object[] row = new Object[3];
        row[0] = collisionSensor;
        row[1] = collisionSensor.getImpact();
        row[2] = collisionSensor.getStatus();
        model.addRow(row);
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        detailsjButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        collisionParamjTable2 = new javax.swing.JTable();
        actionjButton8 = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        detailsjButton1.setText("View Details");
        detailsjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsjButton1ActionPerformed(evt);
            }
        });

        collisionParamjTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sensors", "Impact", "Status"
            }
        ));
        jScrollPane2.setViewportView(collisionParamjTable2);

        actionjButton8.setText("Action");
        actionjButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionjButton8ActionPerformed(evt);
            }
        });

        backjButton1.setText("<<");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Collision Sensor Parameter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(backjButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(actionjButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1)))
                .addGap(297, 297, 297))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addGap(85, 85, 85)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actionjButton8)
                    .addComponent(backjButton1))
                .addGap(325, 325, 325))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actionjButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionjButton8ActionPerformed
        int selectedRow = collisionParamjTable2.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please Select a Row");
            return;
        }

        final JFrame dialog = new JFrame();
        dialog.pack();
        String message = JOptionPane.showInputDialog(dialog,"Type Message to be sent to TrafficManager", null);
         if(message.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please Enter The Message To Be Sent");
            
        }
        else
        {
        WorkRequest request = new WorkRequest();
        request.setMessage(message);
        
        request.setStatus("Sent");
        request.setDriverAcknowledgement("Acknowledged");

        Organisation org = null;
        for(Organisation organisation: enterprise.getOrganisationDir().getOrganisationList())
        if(organisation instanceof TransportationOrganisation)
        {
            org = organisation;
            request.setOrganisation(organisation);
            break;
        }
        if(org!=null)
        {
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null,"Request Sent to Transport Department Admin");
        }
    }//GEN-LAST:event_actionjButton8ActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
userProcessContainer.remove(this);
CardLayout layout = (CardLayout) userProcessContainer.getLayout();
layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void detailsjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsjButton1ActionPerformed
 SensorAdminWorkRequestJPanel sawjp = new SensorAdminWorkRequestJPanel(userProcessContainer,userAccount,sensorsOrganisation, enterprise);
        userProcessContainer.add("SensorDetails",sawjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_detailsjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionjButton8;
    private javax.swing.JButton backjButton1;
    private javax.swing.JTable collisionParamjTable2;
    private javax.swing.JButton detailsjButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
