/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SensorsAdmin;

import business.Enterprise.Enterprise;
import business.Organisation.ConstructionOrganisation;
import business.Organisation.Organisation;
import business.Organisation.SensorsOrganisation;
import business.Sensor.CollisionSensor;
import business.Sensor.CracksSensor;
import business.UserAccount.UserAccount;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.CracksSensorThread;

/**
 *
 * @author aksha
 */
public class CrackSensorParamJPanel extends javax.swing.JPanel {
 private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private CracksSensor cs;

    /**
     * Creates new form CollisionSensorParamJPanel
     */
    public CrackSensorParamJPanel(JPanel userProcessContainer,UserAccount userAccount,Organisation organisation,Enterprise enterprise,CracksSensor cs){
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.cs = cs;
        CracksSensorThread cst = new CracksSensorThread(userAccount, organisation, this, cs);
        cst.start();
       
       
    }
    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel)crackSensorParamjTable1.getModel();
        
        Object[] row = new Object[3];
        row[0] = cs;
        row[1] = cs.getWeight();
        row[2] = cs.getStatus();
        model.addRow(row);
       
    }
   
    /**
     * Creates new form CrackSensorParamJPanel
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        crackSensorParamjTable1 = new javax.swing.JTable();
        backjButton1 = new javax.swing.JButton();
        actionjButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        crackSensorParamjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sensors", "Weight", "Status"
            }
        ));
        jScrollPane1.setViewportView(crackSensorParamjTable1);

        backjButton1.setText("<<");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        actionjButton8.setText("Action");
        actionjButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionjButton8ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cracks Sensor Parameters");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backjButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(actionjButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel1)))
                .addGap(338, 338, 338))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(83, 83, 83)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actionjButton8)
                    .addComponent(backjButton1))
                .addGap(137, 137, 137))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void actionjButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionjButton8ActionPerformed
         int selectedRow = crackSensorParamjTable1.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please Select Sensor");
            return;
        }

      
        final JFrame dialog = new JFrame();
        dialog.pack();
        String message = JOptionPane.showInputDialog(dialog,"Type the Message to be sent to Construction Department",null);
         if(message.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please Enter The Message To Be Sent");
            
        }
        else
        {
         
        WorkRequest request = new WorkRequest();
        request.setMessage(message);
        
        request.setStatus("Sent");
        request.setDriverAcknowledgement("Pending");

        Organisation org = null;
        for(Organisation organisation: enterprise.getOrganisationDir().getOrganisationList())
        if(organisation instanceof ConstructionOrganisation)
        {
            org = organisation;
            request.setOrganisation(organisation);
            break;
        }
        if(org!=null)
        {
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null,"Request Sent to Construction Department");
         
        }
        
    }//GEN-LAST:event_actionjButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionjButton8;
    private javax.swing.JButton backjButton1;
    private javax.swing.JTable crackSensorParamjTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
