/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SensorsAdmin;

import business.Enterprise.Enterprise;
import business.Organisation.Organisation;
import business.Organisation.SensorsOrganisation;
import business.Organisation.WeatherOrganisation;
import business.UserAccount.UserAccount;
import business.WorkQueue.DriverApprovalWorkRequest;
import business.WorkQueue.WorkQueue;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aksha
 */
public class SensorAdminWorkRequestJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Organisation organisation ;
    
    /**
     * Creates new form SensorAdminWorkRequestJPanel
     */
    public SensorAdminWorkRequestJPanel(JPanel userProcessContainer,UserAccount userAccount,Organisation organisation,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.organisation = organisation;
        populateWorkRequest();
        
    }
    public void populateWorkRequest()
    {
        DefaultTableModel model =(DefaultTableModel)liquidAndIcyRoadSensorjTable1.getModel();
        model.setRowCount(0);
        for(WorkRequest workRequest: userAccount.getWorkQueue().getWorkRequestList())
        {
            Object[] row = new Object[5];
            row[0] = workRequest.getMessage();
            row[1] = workRequest.getOrganisation();
            row[2] = workRequest.getStatus();
            //String result = ((DriverApprovalWorkRequest) workRequest).getTestResult();
            //row[3] = result == null ? "Pending" : result;
            row[3] = workRequest.getRequestDate();
            row[4] = workRequest.getResolveDate();
            
            model.addRow(row);
            
        }
            
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        liquidAndIcyRoadSensorjTable1 = new javax.swing.JTable();
        backjButton1 = new javax.swing.JButton();

        liquidAndIcyRoadSensorjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MESSAGE", "Assigned to", "Status", "Requested Date", "Resolved Date"
            }
        ));
        jScrollPane1.setViewportView(liquidAndIcyRoadSensorjTable1);

        backjButton1.setText("<<");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backjButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(backjButton1)
                .addContainerGap(349, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable liquidAndIcyRoadSensorjTable1;
    // End of variables declaration//GEN-END:variables
}
