/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DriverRole;

import business.Enterprise.Enterprise;
import business.Organisation.DriverOrganisation;
import business.Organisation.Organisation;
import business.UserAccount.UserAccount;
import business.WorkQueue.DriverApprovalWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import sun.audio.*;
import java.io.*;
import java.awt.event.*;



/**
 *
 * @author aksha
 */
public class DriverWorkAreaJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
private UserAccount userAccount;
private Enterprise enterprise;
    /**
     * Creates new form DriverWorkAreaJPanel
     */
    public DriverWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        populateDriverWorkAreaTable();
    }
    /*public static void music() 
    {
        AudioPlayer MGP = AudioPlayer.player;
        AudioStream BGM;
        AudioData MD;
        ContinuousAudioDataStream loop = null;
        
        try{
        BGM = new AudioStream(new FileInputStream("programaudio.aac"));
        MD = BGM.getData();
        loop = new ContinuousAudioDataStream(MD);
        }catch(IOException error){}
        MGP.start(loop);
    }*/
    public void populateDriverWorkAreaTable()
    {
        DefaultTableModel model = (DefaultTableModel)driverInfoJTable.getModel();
        model.setRowCount(0);
        Organisation org = null;
        for(Organisation organisation : enterprise.getOrganisationDir().getOrganisationList())
            if(organisation instanceof DriverOrganisation)
            {
                org = organisation;
                break;
            }
        for(WorkRequest request: org.getWorkQueue().getWorkRequestList())
        {
            
            {
                DriverApprovalWorkRequest r=(DriverApprovalWorkRequest)request;
                Object[] row = new Object[2];
                row[0] = r;
               
                row[1] = r.getReceiver();
                
                model.addRow(row);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jToggleButton1 = new javax.swing.JToggleButton();
        assignJButton = new javax.swing.JButton();
        button1 = new java.awt.Button();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        driverInfoJTable = new javax.swing.JTable();
        weatherJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        trafficjButton2 = new javax.swing.JButton();
        crackjButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });

        button1.setLabel("button1");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        driverInfoJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(driverInfoJTable);

        weatherJButton.setText("Weather Alert");
        weatherJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weatherJButtonActionPerformed(evt);
            }
        });

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        trafficjButton2.setText("Traffic Alert");
        trafficjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trafficjButton2ActionPerformed(evt);
            }
        });

        crackjButton3.setText("Cracks Alert");
        crackjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crackjButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Driver Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(refreshJButton)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(weatherJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(trafficjButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(crackjButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1)))
                .addGap(206, 206, 206))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(refreshJButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(weatherJButton)
                .addGap(35, 35, 35)
                .addComponent(trafficjButton2)
                .addGap(32, 32, 32)
                .addComponent(crackjButton3)
                .addContainerGap(233, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = driverInfoJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        WorkRequest request = (WorkRequest)driverInfoJTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Pending");
        populateDriverWorkAreaTable(); 
        

    }//GEN-LAST:event_assignJButtonActionPerformed

    private void weatherJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weatherJButtonActionPerformed
        
       InputStream in;
        try{
            in = new FileInputStream(new File("weather.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
                    
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        /*int selectedRow = driverInfoJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please Select the message");
            return;
        }

        DriverApprovalWorkRequest request = (DriverApprovalWorkRequest)driverInfoJTable.getValueAt(selectedRow, 0);
        Date date = new Date();
        request.setResponse(date);

        DriverActionJPanel dajp = new DriverActionJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("processWorkRequestJPanel", dajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        music();*/
    
    }//GEN-LAST:event_weatherJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void trafficjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trafficjButton2ActionPerformed
 InputStream in;
        try{
            in = new FileInputStream(new File("traffic.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
                    
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }      // TODO add your handling code here:
    }//GEN-LAST:event_trafficjButton2ActionPerformed

    private void crackjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crackjButton3ActionPerformed
 InputStream in;
        try{
            in = new FileInputStream(new File("cracks.wav"));
            AudioStream audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
                    
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }       // TODO add your handling code here:
    }//GEN-LAST:event_crackjButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private java.awt.Button button1;
    private javax.swing.JButton crackjButton3;
    private javax.swing.JTable driverInfoJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton trafficjButton2;
    private javax.swing.JButton weatherJButton;
    // End of variables declaration//GEN-END:variables

        
    }
