/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StoreAdminRole;

import business.MasterInventoryDirectory;
import business.Pharma;
import business.PharmaDirectory;
import business.Store;
import business.StoreDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author aksha
 */
public class StoreWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private StoreDirectory storeDirectory;
    private PharmaDirectory pharmaDirectory;
    

    /**
     * Creates new form StoreJPanel
     */
    public StoreWorkAreaJPanel(JPanel userProcessContainer, StoreDirectory storeDirectory, PharmaDirectory pharmaDirectory){
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.storeDirectory= storeDirectory;
        this.pharmaDirectory = pharmaDirectory;
       
        storejComboBox.removeAllItems();
        for (Store s : storeDirectory.getStoreList()) {
            storejComboBox.addItem(s);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        storejComboBox = new javax.swing.JComboBox();
        gojButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Store Name");

        storejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        storejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storejComboBoxActionPerformed(evt);
            }
        });

        gojButton1.setText("GO>>");
        gojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gojButton1ActionPerformed(evt);
            }
        });

        jButton1.setText("Reporting");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(storejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(gojButton1)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(storejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gojButton1))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gojButton1ActionPerformed
        Store st = (Store) storejComboBox.getSelectedItem();
        StoreDetailsJPanel sd = new StoreDetailsJPanel(userProcessContainer,st,pharmaDirectory);
        userProcessContainer.add("StoreDetailsPanel", sd);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_gojButton1ActionPerformed

    private void storejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storejComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Store s = (Store)storejComboBox.getSelectedItem();
       MasterInventoryDirectory masterInventoryDirectory = s.getMasterInventoryDirectory();
        InventoryReportJPanel vj = new InventoryReportJPanel(userProcessContainer, masterInventoryDirectory);
        userProcessContainer.add("ViewDetailsPanel", vj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gojButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox storejComboBox;
    // End of variables declaration//GEN-END:variables
}
