/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StoreAdminRole;

import business.InventoryItem;
import javax.swing.JPanel;

/**
 *
 * @author aksha
 */
public class ViewInventoryItemJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    InventoryItem inventoryItem;

    /**
     * Creates new form ViewInventoryItemJPanel
     */
    public ViewInventoryItemJPanel(JPanel userProcessConatainer,InventoryItem inventoryItem) {
        initComponents();
        this.userProcessContainer = userProcessConatainer;
        this.inventoryItem = inventoryItem;
        namejText.setText(inventoryItem.getDrug().getDrugName());
        drugpricejText.setText(Integer.toString(inventoryItem.getDrug().getPrice()));
        stockjText.setText(Integer.toString(inventoryItem.getStock()));
        tpricejText.setText(Integer.toString(inventoryItem.getSalesPrice()));
        drugidjText.setText(Integer.toString(inventoryItem.getDrug().getDrugID()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drugidjText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        stockjText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        backjButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        namejText = new javax.swing.JTextField();
        drugpricejText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tpricejText = new javax.swing.JTextField();

        jLabel5.setText("Drug ID");

        stockjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockjTextActionPerformed(evt);
            }
        });

        jLabel11.setText("Current Stock");

        backjButton1.setText("<<BACK");

        jLabel1.setText("Name");

        namejText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namejTextActionPerformed(evt);
            }
        });

        jLabel6.setText("Price");

        jLabel2.setText("Total Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addComponent(backjButton1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namejText, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tpricejText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockjText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drugidjText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drugpricejText, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(namejText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(drugpricejText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tpricejText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(drugidjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(stockjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(backjButton1)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stockjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockjTextActionPerformed

    private void namejTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namejTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namejTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JTextField drugidjText;
    private javax.swing.JTextField drugpricejText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField namejText;
    private javax.swing.JTextField stockjText;
    private javax.swing.JTextField tpricejText;
    // End of variables declaration//GEN-END:variables
}
