/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CVSAdminRole;

import business.Drug;
import business.DrugDirectory;
import business.Pharma;
import business.PharmaDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aksha
 */
public class ManageDrugDirectoryJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
   private Pharma p;
   
    

    /**
     * Creates new form ManageDrugDirectoryJPanel
     */
    public ManageDrugDirectoryJPanel(JPanel userProcessContainer, Pharma p) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.p = p;
        pharmajText.setText(p.getPharmaName());
        populateTable();
    }
public void populateTable() {
     int rowCount = drugdirectoryjTable1.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)drugdirectoryjTable1.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            dtm.removeRow(i);
        }
        
        for (Drug d : p.getDrugDirectory().getDrugList()) {
            Object row[] = new Object[5];   
            row[0] = d;
            row[1] = d.getExpiryDate();
            row[2] = d.getPrice();
            row[3] = d.getDrugID();
            row[4] = d.getCurrentStock();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        drugdirectoryjTable1 = new javax.swing.JTable();
        viewjButton1 = new javax.swing.JButton();
        addjButton2 = new javax.swing.JButton();
        deletejButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pharmajText = new javax.swing.JTextField();

        drugdirectoryjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Expiry Date", "Price", "Drug ID", "Current Stock"
            }
        ));
        jScrollPane1.setViewportView(drugdirectoryjTable1);

        viewjButton1.setText("View");
        viewjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewjButton1ActionPerformed(evt);
            }
        });

        addjButton2.setText("Add");
        addjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButton2ActionPerformed(evt);
            }
        });

        deletejButton3.setText("Delete");
        deletejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("<<BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Pharma Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(viewjButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletejButton3)
                            .addGap(78, 78, 78)
                            .addComponent(addjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pharmajText, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(pharmajText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewjButton1)
                    .addComponent(deletejButton3)
                    .addComponent(addjButton2))
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addGap(128, 128, 128))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButton2ActionPerformed
        AddDrugJPanel ad = new AddDrugJPanel(userProcessContainer,p);
        userProcessContainer.add("CVSWorkArea",ad);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_addjButton2ActionPerformed

    private void viewjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewjButton1ActionPerformed
int selectedRow = drugdirectoryjTable1.getSelectedRow();
if (selectedRow>=0)
{       Drug d = (Drug)drugdirectoryjTable1.getValueAt(selectedRow, 0);
        ViewDrugsJPanel panel= new ViewDrugsJPanel(userProcessContainer,d); 
        userProcessContainer.add("panel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    
} 
 else{
            JOptionPane.showMessageDialog(null,"Please Select a Row", "WARNING", JOptionPane.INFORMATION_MESSAGE);//key part dont knw
        }         // TODO add your handling code here:
    }//GEN-LAST:event_viewjButton1ActionPerformed

    private void deletejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButton3ActionPerformed
  int row = drugdirectoryjTable1.getSelectedRow();
        
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Drug d = (Drug)drugdirectoryjTable1.getValueAt(row, 0);
        p.getDrugDirectory().removeDrug(d);
        populateTable();        // TODO add your handling code here:
    }//GEN-LAST:event_deletejButton3ActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton2;
    private javax.swing.JButton deletejButton3;
    private javax.swing.JTable drugdirectoryjTable1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pharmajText;
    private javax.swing.JButton viewjButton1;
    // End of variables declaration//GEN-END:variables
}
