/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CVSAdminRole;

import business.Drug;
import business.DrugDirectory;
import business.Store;
import business.StoreDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aksha
 */
public class ManageStoreDirectoryJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private StoreDirectory storeDirectory;
    

    /**
     * Creates new form ManageStoreDirectoryJPanel
     */
    public ManageStoreDirectoryJPanel(JPanel userProcessContainer,StoreDirectory storeDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.storeDirectory=storeDirectory;
        populateTable();
    }
public void populateTable(){
    DefaultTableModel dtm = (DefaultTableModel)storejTable1.getModel();
        dtm.setRowCount(0);
        for (Store s : storeDirectory.getStoreList()) {
            Object row[] = new Object[3];   
            row[0] = s;
            row[1] = s.getArea();
            row[2] = s.getZipcode();
            dtm.addRow(row);
            
        }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        storejTable1 = new javax.swing.JTable();
        storejButton1 = new javax.swing.JButton();
        deletejButton3 = new javax.swing.JButton();
        backjButton4 = new javax.swing.JButton();

        jButton2.setText("View ");

        storejTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Store Name", "Location", "ZipCode"
            }
        ));
        jScrollPane1.setViewportView(storejTable1);

        storejButton1.setText("Add Store");
        storejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storejButton1ActionPerformed(evt);
            }
        });

        deletejButton3.setText("Delete");
        deletejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButton3ActionPerformed(evt);
            }
        });

        backjButton4.setText("<<BACK");
        backjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backjButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deletejButton3)
                        .addGap(18, 18, 18)
                        .addComponent(storejButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletejButton3)
                    .addComponent(backjButton4)
                    .addComponent(storejButton1))
                .addContainerGap(148, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton4ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton4ActionPerformed

    private void storejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storejButton1ActionPerformed
        AddStoreJPanel ad = new AddStoreJPanel(userProcessContainer,storeDirectory);
        userProcessContainer.add("CVSWorkArea",ad);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);         // TODO add your handling code here:
    }//GEN-LAST:event_storejButton1ActionPerformed

    private void deletejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButton3ActionPerformed
   int selectedRow=storejTable1.getSelectedRow();
        if(selectedRow>=0)
        {
            int dialogResult=JOptionPane.showConfirmDialog(null, "Please confirm whether to delete","Confirmation",JOptionPane.INFORMATION_MESSAGE);
            if(dialogResult==JOptionPane.YES_OPTION);
            {
                Store s=(Store)storejTable1.getValueAt(selectedRow,0);
                storeDirectory.removeStore(s);
                
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select account to delete", "delete account", JOptionPane.INFORMATION_MESSAGE);
        }
        
        refreshTable();
    }//GEN-LAST:event_deletejButton3ActionPerformed
public void refreshTable(){
        int rowCount = storejTable1.getRowCount();
        DefaultTableModel model = (DefaultTableModel) storejTable1.getModel();
        for(int i=rowCount-1;i>=0;i--){
            model.removeRow(i);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton4;
    private javax.swing.JButton deletejButton3;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton storejButton1;
    private javax.swing.JTable storejTable1;
    // End of variables declaration//GEN-END:variables
}
