/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CVSAdminRole;

import business.DrugDirectory;
import business.Pharma;
import business.PharmaDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author aksha
 */
public class PharmaLoginJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private PharmaDirectory pharmaDirectory;
    
    

    /**
     * Creates new form PharmaLoginJPanel
     */
    public PharmaLoginJPanel(JPanel userProcessContainer,PharmaDirectory pharmaDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pharmaDirectory = pharmaDirectory;
        
        pharmajComboBox.removeAllItems();
        for(Pharma p:pharmaDirectory.getPharmaList()){
            pharmajComboBox.addItem(p);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pharmajComboBox = new javax.swing.JComboBox();
        loginjButton1 = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();

        jLabel1.setText("Pharma Name");

        pharmajComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        loginjButton1.setText("Login");
        loginjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButton1ActionPerformed(evt);
            }
        });

        backjButton1.setText("<<BACK");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(backjButton1))
                .addGap(31, 31, 31)
                .addComponent(pharmajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(loginjButton1)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pharmajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginjButton1))
                .addGap(18, 18, 18)
                .addComponent(backjButton1)
                .addContainerGap(185, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButton1ActionPerformed
        Pharma p =(Pharma)pharmajComboBox.getSelectedItem();
        ManageDrugDirectoryJPanel md =new ManageDrugDirectoryJPanel(userProcessContainer,p);
        userProcessContainer.add("Add Supplier",md);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_loginjButton1ActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);         // TODO add your handling code here:
    }//GEN-LAST:event_backjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginjButton1;
    private javax.swing.JComboBox pharmajComboBox;
    // End of variables declaration//GEN-END:variables
}
