/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnterpriseAdminRole;

import business.Driver.Driver;
import business.Enterprise.Enterprise;
import business.Organisation.DriverOrganisation;
import business.Organisation.Organisation;
import business.Organisation.OrganisationDirectory;
import business.Person.Person;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aksha
 */
public class DriverJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
private OrganisationDirectory organisationDirectory;
    /**
     * Creates new form DriverJPanel
     */
    public DriverJPanel(JPanel userProcessContainer,OrganisationDirectory organisationDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organisationDirectory = organisationDirectory;
        populate();
    }
    public void populate()
    {
        DefaultTableModel model = (DefaultTableModel)driverjTable1.getModel();
        model.setRowCount(0);
        Organisation organisation = null;
        for(Organisation org : organisationDirectory.getOrganisationList())
            if(org instanceof DriverOrganisation)
            {
                organisation = (DriverOrganisation)org;
               for(Person p : organisation.getPersonDir().getPersonList())
                   if(p instanceof Driver)
                   {
                        Driver d = (Driver)p;
                        Object[] row = new Object[2];
                        row[0] = d;
                        row[1] = d.getEmail();
                         model.addRow(row);
                   }
          
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        driverjTable1 = new javax.swing.JTable();
        backjButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        driverjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email"
            }
        ));
        jScrollPane1.setViewportView(driverjTable1);

        backjButton1.setText("<<");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("List Of Registered Drivers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backjButton1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1)))
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(backjButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
layout.previous(userProcessContainer);// TODO add your handling code here:
    }//GEN-LAST:event_backjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JTable driverjTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
