/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnterpriseAdminRole;

import business.Driver.Driver;
import business.Organisation.DriverOrganisation;
import business.Organisation.Organisation;
import business.Organisation.OrganisationDirectory;
import business.Person.Person;
import java.awt.CardLayout;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aksha
 */
public class ManageDriversJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private OrganisationDirectory organisationDirectory;
    

    /**
     * Creates new form ManageDriversJPanel
     */
    public ManageDriversJPanel(JPanel userProcessContainer,OrganisationDirectory organisationDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organisationDirectory = organisationDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressjTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dNamejTextField2 = new javax.swing.JTextField();
        malejRadioButton1 = new javax.swing.JRadioButton();
        femalejRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        licenseNumberjTextField5 = new javax.swing.JTextField();
        backjButton1 = new javax.swing.JButton();
        addDriverjButton2 = new javax.swing.JButton();
        viewjButton1 = new javax.swing.JButton();
        addressLine1jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addressLine2jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        emailjTextField1 = new javax.swing.JTextField();

        jTextField3.setText("jTextField3");

        addressjTextArea1.setColumns(20);
        addressjTextArea1.setRows(5);
        jScrollPane1.setViewportView(addressjTextArea1);

        jLabel2.setText("Driver Name");

        jLabel3.setText("Gender");

        jLabel4.setText("Address Line 1");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Driver Information");

        buttonGroup1.add(malejRadioButton1);
        malejRadioButton1.setText("Male");

        buttonGroup1.add(femalejRadioButton2);
        femalejRadioButton2.setText("Female");

        jLabel7.setText("License Number");

        backjButton1.setText("<<");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        addDriverjButton2.setText("Add Driver");
        addDriverjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDriverjButton2ActionPerformed(evt);
            }
        });

        viewjButton1.setText("View");
        viewjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewjButton1ActionPerformed(evt);
            }
        });

        addressLine1jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressLine1jTextField1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Address Line 2");

        jLabel1.setText("Email");

        emailjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailjTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7)
                            .addComponent(backjButton1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addDriverjButton2)
                                .addGap(74, 74, 74)
                                .addComponent(viewjButton1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(licenseNumberjTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailjTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addressLine2jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addressLine1jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dNamejTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(malejRadioButton1)
                                    .addGap(18, 18, 18)
                                    .addComponent(femalejRadioButton2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel5)))
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dNamejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(malejRadioButton1)
                    .addComponent(femalejRadioButton2))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLine1jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addressLine2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(emailjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(licenseNumberjTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backjButton1)
                    .addComponent(addDriverjButton2)
                    .addComponent(viewjButton1))
                .addGap(227, 227, 227))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDriverjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDriverjButton2ActionPerformed

String dName = dNamejTextField2.getText();
String address = addressjTextArea1.getText();
String email = emailjTextField1.getText();
Driver driver = new Driver();
if(malejRadioButton1.isSelected())
{
    driver.setMale("Male");
}else
{
    driver.setFemale("Female");
}
driver.setDriverName(dName);
driver.setAddress1(address);
driver.setEmail(email);
driver.getLicenseNumber();

Organisation organisation = null;
 for(Organisation org : organisationDirectory.getOrganisationList())
     if(org instanceof DriverOrganisation)
     {
         organisation = org;
     }
         organisation.getPersonDir().getPersonList().add(driver);
          JOptionPane.showMessageDialog(null,"Driver Added");
    }//GEN-LAST:event_addDriverjButton2ActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
layout.previous(userProcessContainer);// TODO add your handling code here:
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void addressLine1jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressLine1jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressLine1jTextField1ActionPerformed

    private void emailjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailjTextField1ActionPerformed

    private void viewjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewjButton1ActionPerformed
DriverJPanel djp = new DriverJPanel(userProcessContainer,organisationDirectory);
userProcessContainer.add("DriverJPPanel",djp);
CardLayout layout = (CardLayout)userProcessContainer.getLayout();
layout.next(userProcessContainer);
    }//GEN-LAST:event_viewjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDriverjButton2;
    private javax.swing.JTextField addressLine1jTextField1;
    private javax.swing.JTextField addressLine2jTextField2;
    private javax.swing.JTextArea addressjTextArea1;
    private javax.swing.JButton backjButton1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dNamejTextField2;
    private javax.swing.JTextField emailjTextField1;
    private javax.swing.JRadioButton femalejRadioButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField licenseNumberjTextField5;
    private javax.swing.JRadioButton malejRadioButton1;
    private javax.swing.JButton viewjButton1;
    // End of variables declaration//GEN-END:variables
}
