/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnterpriseAdminRole;

import business.Organisation.Organisation;
import business.Organisation.OrganisationDirectory;
import business.Person.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.SystemAdminRole.ManageEnterpriseJPanel;

/**
 *
 * @author aksha
 */
public class ManagePersonJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private OrganisationDirectory organisationDir;

    /**
     * Creates new form MangeEmployeeJPanel
     */
    public ManagePersonJPanel(JPanel userProcessContainer, OrganisationDirectory organisationDir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organisationDir = organisationDir;
        populateOrganisationComboBox();
        populateOrganisationEmpComboBox();
    }

    public void populateOrganisationComboBox() {
        organisationJComboBox.removeAllItems();

        for (Organisation organisation : organisationDir.getOrganisationList()) {
            organisationJComboBox.addItem(organisation);
        }
    }

    public void populateOrganisationEmpComboBox() {
        organisationEmpJComboBox.removeAllItems();

        for (Organisation organisation : organisationDir.getOrganisationList()) {
            organisationEmpJComboBox.addItem(organisation);
        }
    }

    private void populateTable(Organisation organisation) {
        DefaultTableModel model = (DefaultTableModel) organisationJTable.getModel();

        model.setRowCount(0);

        for (Person person : organisation.getPersonDir().getPersonList()) {
            Object[] row = new Object[2];
            row[0] = person.getPersonID();
            row[1] = person.getName();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        organisationJTable = new javax.swing.JTable();
        addJButton = new javax.swing.JButton();
        organisationJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        organisationEmpJComboBox = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Organisation");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        organisationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organisationJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, 120));

        addJButton.setText("Create Employee");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        organisationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organisationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organisationJComboBoxActionPerformed(evt);
            }
        });
        add(organisationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 150, -1));

        jLabel1.setText("Organisation");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 140, -1));

        organisationEmpJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(organisationEmpJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed

        Organisation organisation = (Organisation) organisationEmpJComboBox.getSelectedItem();
        String name = nameJTextField.getText();
        Validation v = new Validation();

        if (organisation == null) {
            JOptionPane.showMessageDialog(null, "Please Enter a Organisation to proceed");
        } else {
            if (!(v.onlyAlphabets(name))) {
                JOptionPane.showMessageDialog(null, "Please enter only alphabets", "Warning Message", JOptionPane.PLAIN_MESSAGE);
            } else if (name.equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(null, "Enterprise can not be blank", "Warning Message", JOptionPane.PLAIN_MESSAGE);
            }else{
                
     
     

            organisation.getPersonDir().createAndAddPerson(name);
            populateTable(organisation);
            nameJTextField.setText("");
        }
    }
    }
    

    public class Validation {

        String regex = "[a-zA-Z]+";

        public boolean onlyAlphabets(String s) {
            if (s.matches(regex)) {
                return true;
            }
            return false;
        }
    }//GEN-LAST:event_addJButtonActionPerformed

    private void organisationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organisationJComboBoxActionPerformed
        Organisation organisation = (Organisation) organisationJComboBox.getSelectedItem();
        if (organisation != null) {
            populateTable(organisation);
        }
    }//GEN-LAST:event_organisationJComboBoxActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox organisationEmpJComboBox;
    private javax.swing.JComboBox organisationJComboBox;
    private javax.swing.JTable organisationJTable;
    // End of variables declaration//GEN-END:variables
}
