/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.TransportDeptManagerRole;

import business.Enterprise.Enterprise;
import business.Organisation.DriverOrganisation;
import business.Organisation.Organisation;
import business.Organisation.TransportationOrganisation;
import business.Organisation.WeatherOrganisation;
import business.UserAccount.UserAccount;
import business.WorkQueue.DriverApprovalWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.WeatherDeptManagerRole.AlertDriverJPanel;

/**
 *
 * @author aksha
 */
public class TransportationDeptManagerJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private TransportationOrganisation transportationOrganisation;
    private Enterprise enterprise;

    /**
     * Creates new form TransportationDeptManagerJPanel
     */
    public TransportationDeptManagerJPanel(JPanel userProcessContainer,UserAccount userAccount,Organisation organisation,Enterprise enterprise) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.transportationOrganisation = (TransportationOrganisation)organisation;
        this.enterprise = enterprise;
        populateTable();
        populateDriverTable();
      
    }
     public void populateDriverTable()
    {
        
        DefaultTableModel model = (DefaultTableModel)tdDriveralertjTable1.getModel();
        model.setRowCount(0);
        Organisation org = null;
        for(Organisation organisation : enterprise.getOrganisationDir().getOrganisationList())
            if(organisation instanceof TransportationOrganisation)
            {
                org = organisation;
                break;
            }
        for(WorkRequest request: userAccount.getWorkQueue().getWorkRequestList())
        {
            
            {
                DriverApprovalWorkRequest r=(DriverApprovalWorkRequest)request;
                Object[] row = new Object[4];
                row[0] = r;
                row[1] = r.getSendTo();
                row[2] = r.getRequest();
                row[3] = r.getResponse();
                model.addRow(row);
            }
            
        }
    }
    
        
        /*request.setStatus("Waiting for Acknowledgement");
            request.setDriverAcknowledgement("Pending");*/
    
    public void populateTable()
    {
         DefaultTableModel model = (DefaultTableModel)tdWorkRequestJTable.getModel();
        
        model.setRowCount(0);
        for(WorkRequest request : transportationOrganisation.getWorkQueue().getWorkRequestList())
        {
            Object[] row = new  Object[5];
            row[0] = request;
            row[1] = request.getStatus();
            row[2] = request.getRequestDate();
            row[3] = request.getResolveDate();
            row[4] = request.getDriverAcknowledgement();
            
            model.addRow(row);
            
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdWorkRequestJTable = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        alertJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tdDriveralertjTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Transportation Department Work Area");

        tdWorkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Status", "Requested Date", "Sensor Acknowledeged Time", "Driver Acknowledged"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tdWorkRequestJTable);

        assignJButton.setText("Acknowledge Sensor Admin");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });

        alertJButton.setText("Alert Driver");
        alertJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertJButtonActionPerformed(evt);
            }
        });

        tdDriveralertjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Send To", "Requested Time ", "Resolved Date"
            }
        ));
        jScrollPane2.setViewportView(tdDriveralertjTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Driver Alert");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assignJButton)
                                .addGap(347, 347, 347)
                                .addComponent(alertJButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(197, 197, 197))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel2)))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alertJButton)
                    .addComponent(assignJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = tdWorkRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please Select a Row" );
            return;
        }

        WorkRequest request = (WorkRequest)tdWorkRequestJTable.getValueAt(selectedRow, 0);
        request.setStatus("completed");
        Date date = new Date();
        request.setResolveDate(date);
        JOptionPane.showMessageDialog(null,"Sensor Admin Acknowledged");
        populateTable();
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void alertJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertJButtonActionPerformed
          
        int selectedRow = tdWorkRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please Select a Row");
            return;
        }
        

        WorkRequest request = (WorkRequest)tdWorkRequestJTable.getValueAt(selectedRow,0);
        
        populateTable();
        TransportAlertDriverJPanel tadjp = new TransportAlertDriverJPanel(userProcessContainer, userAccount, enterprise);
        userProcessContainer.add("AlertDriverWorkArea",tadjp);
        CardLayout layout =(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_alertJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alertJButton;
    private javax.swing.JButton assignJButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tdDriveralertjTable1;
    private javax.swing.JTable tdWorkRequestJTable;
    // End of variables declaration//GEN-END:variables
}
